version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/Goods
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Vintage38
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=DEBUG
      - LOGGING_LEVEL_ORG_HIBERNATE_TYPE=TRACE
      - SPRING_SECURITY_USER_NAME=root
      - SPRING_SECURITY_USER_PASSWORD=root
      - SPRING_SECURITY_USER_ROLES=manager
      - SPRING_CACHE_TYPE=none
      - SPRING_WEB_RESOURCES_ADD-MAPPINGS=true
    networks:
      - spring-mysql
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=Goods
      - MYSQL_ROOT_PASSWORD=Vintage38
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-mysql
    expose:
      - "3306"

volumes:
  db-data:

networks:
  spring-mysql:
